#!/bin/bash

# Starting sshd insode the container
/usr/sbin/sshd

sed -i \
    -e "s#TARGETHOST#${TARGETHOST}#g" \
    -e "s#TARGETPORT#${TARGETPORT}#g" \
    /root/.tsung/tsung.xml

LOGDIR=$(/usr/bin/tsung -f /root/.tsung/tsung.xml start | grep "Log directory is" | sed 's/"//g' | awk {'print $4'})

cd $LOGDIR && \
    /usr/lib/tsung/bin/tsung_stats.pl

